# Generated by Django 4.1 on 2022-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toniTodo', '0002_alter_todo_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
